### ISSUE TITLE
Velocity command interface

### ISSUE THREAD

**Issue by fafux** [PickNikRobotics/abb_ros2#51]
Hi,
I am trying to control an ABB robot in simulation with the command interface in velocity with ROS2 foxy. The values of the joint velocities states, in simulation, are changing but the robot is not moving. While if I try to move the robot using the position command interface I can do it.
Is it possible to move the robot only using the velocity command interface? If so, is there any example on how to do it?
Thanks.

**Comment by tanmay2798** [comment]
did you get answer to it?

**Comment by fafux** [comment]
No but on ROS2 Humble the velocity command interface works on real hardware. You should launch this [RAPID](https://github.com/PickNikRobotics/abb_ros2/blob/rolling/robot_studio_resources/velocity_control_example/TRob1Main.mod) on the robot to use the hardware interface in velocity.

**Comment by Yadunund** [comment]
I was able to implement velocity-only control by setting the EGM gain to 0 in the EGM Motion setup which makes the robot's controller ignore position references. See control law described on [pg 21](https://library.e.abb.com/public/4c9bfa6a4e9542bf9386c87f5377a27f/3HAC073319%20AM%20Externally%20Guided%20Motion%20RW6-en.pdf?x-sign=UrpOfQfx8L5Lw8/ul4N/yqOLjsiscAk+vtmgOADospPrIQQm9iNmdokJj+7Wqd3e). This also required me to set the `Level` to `Raw` (from `Filtering)` in the EGM motion setup. I still kept the position and velocity as command interfaces on the ROS 2 side.
It worked well but at some point I realized the robot doesn't converge to the goal very nicely but perhaps this is something that could be fixed with the PID values on the joint_trajectory_controller side.
